### PR TITLE
Select by index mask

### PR DESCRIPTION
**Pull request by jwittenbach**
Implements feature request #156.

Added an optional `returnMask` keyword argument to `Series.selectByIndex` which returns the mask used during the selection as an additional return value. Default value is `False`.

### CODE REVIEW

**Comment by freeman-lab** [comment]
LGTM, thanks for the fix @jwittenbach !

**Comment by jwittenbach** [comment]
I'm looking at the diff on this and something strange happened here. These were actually the changes that I had meant to submit in a different PR addressing the fact that my multi-index code was directly creating the resulting `Series` objects rather than using `Series._constructor`. The change referenced in this PR still needs to be made.

**Comment by freeman-lab** [comment]
Oh oops, I somehow missed that. Feel free to submit a new PR, and probably change the title/description on this one.

**Comment by jwittenbach** [comment]
Yeah, working on it now. Just going to add a unit test for the new functionality, and then I'll submit it.

**Pull request merged**
