### PR TITLE
Update for Travis CI to test against spark 2.0

### PR DESCRIPTION
**Pull request by boazmohar**
Address #359

### CODE REVIEW

**Comment by jwittenbach** [comment]
Well look at that -- awesome! 👍

**Comment by freeman-lab** [comment]
Well that was straightforward 🎉  thanks @boazmohar ! Can you add a note to the README as part of this PR saying that it works with Spark 2.0.0?

**Comment by boazmohar** [comment]
Yep, was very easy. I guess the parts that changed a lot in 2.0 are `DataFrame` and `Dataset` not `RDD`'s.

**Comment by lingerlyn** [comment]
I've been thinking that it would be interesting to see if we could get any speed-ups by switching to `DataFrames` -- haven't had to play around with it yet though.

**Comment by jwittenbach** [comment]
I've been thinking that it would be test whether there might be any speed-up in switching things to `DataFrames` -- though I haven't had any time to play with it.

**Comment by freeman-lab** [comment]
Yeah agreed @jwittenbach, we should definitely look into that, I think the `Dataset` API may be what we want to look at. But in the meantime let's merge this in, good to make clear it's working with the latest version.

**Pull request merged**
