### PR TITLE
Missing split argument for BoltArraySpark in base.element_wise

### LINKED ISSUE #316: Negative Value Errors for Images
When using the `images.minus()` function, sometimes the values of some pixels may become negative.  

To correct for this, I would like to shift the whole image by a scalar value (The minimum of the difference between the images).  However, after doing the minus call, anytime I try to access the new image object, I get this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/thunder/images/images.py", line 191, in map
  File "build/bdist.linux-x86_64/egg/thunder/base.py", line 460, in _map
  File "build/bdist.linux-x86_64/egg/bolt/spark/array.py", line 141, in map
  File "build/bdist.linux-x86_64/egg/bolt/spark/array.py", line 94, in _align
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

Thus, I'm not able to calculate the minimum value across the images to then adjust.

A current workaround is to convert the `image` object to an RDD, calculate the minimum, and adjust the minimum value as an rdd, then do `td.images.fromrdd()` to get back to an RDD.

### PR DESCRIPTION
**Pull request by boazmohar**
fixes #316

### CODE REVIEW

**Comment by boazmohar** [comment]
@freeman-lab Something weird happened with the python 3.5 test. Never seen that error before.

**Comment by freeman-lab** [comment]
Yeah me neither, I just restarted the build.

**Comment by freeman-lab** [comment]
Seems to be running normally now...

**Comment by freeman-lab** [comment]
yay!

**Pull request merged**
