### PR TITLE
nrecords attribute in Data

### PR DESCRIPTION
**Pull request by industrial-sloth**
This PR adds an `nrecords` attribute to `Data` objects, which caches the result of calling `count` on the RDD. 

`nrecords` replaces the `nimages` attribute in `Images` objects. The `nrows` attribute in `RowMatrix` objects is now an alias for `nrecords`. 

`Blocks` retain their `nimages` attribute while gaining `nrecords`. For Blocks `nimages` refers to the number of records in the original Images object, while `nrecords` has the usual interpretation as the number of records in the Blocks RDD.

### CODE REVIEW

**Comment by industrial-sloth** [comment]
When done, this should resolve issue #104 (let's see, is github smart enough to link this correctly?)

**Comment by freeman-lab** [comment]
@industrial-sloth great! Pulled it down locally and did some testing, I think the consistency of these new `__repr__`'s is a big improvement. LGTM, feel free to merge once you resolve the conflicts.

**Comment by industrial-sloth** [comment]
Oops, missed fixing some tests that got added as part of the merge. Hopefully this last commit will do it.

**Comment by industrial-sloth** [comment]
Ha - ok, the merge of the new aggregate regions code just added *more* tests that need `nimages` converted to `nrecords`. So long as we don't merge any more code in the next 10 minutes, this *next* commit should do it.

**Comment by freeman-lab** [comment]
LGTM, merging it in. Thanks @industrial-sloth !

**Pull request merged**
